# Asset evaluation {#asset}

## Index trend (6 months)^[Data are from [Yahoo Finance](https://finance.yahoo.com/).]

```{r}
Yahoo = c(USDKRW = "KRW=X",
          `S&P500` = "^GSPC",
          NASDAQ = "^IXIC",
          KOSPI = "^KS11",
          KOSDAQ = "^KQ11",
          REIT = "^WILREIT",
          Gold = "GC=F",
          Copper = "HG=F",
          Oil = "CL=F")

Index = Yahoo %>% imap_dfr(~{
  read_html(file.path("https://finance.yahoo.com/quote", .x, "history"), which = 1, header = T) %>% 
    mutate(Category = .y)
}) %>% rename(Close = "Close*")

Index$Date %<>%
  str_match("([^ ,]+) ([^ ,]+), ([^ ,]+)") %>% 
  .[, -1] %>% 
  as_tibble %>% 
  setNames(c("m", "d", "y")) %>% 
  mutate(m = match(m, month.abb), date = str_c(y, m, d, sep = "-")) %>% 
  pull(date) %>% 
  as.Date

Index %<>% mutate(across(-c(Date, Volume, Category), ~str_replace(., ",", "") %>% as.numeric))

index_plot = function(indexdata, category, title) {
  Index %>% filter(Category == category & !is.na(Close)) %>%
    ggplot(mapping = aes(x = Date, y = Close)) + 
    geom_ribbon(mapping = aes(ymin = Low, ymax = High), fill = "blue", alpha = 0.15) +
    geom_line(color = "blue", size = 1) +
    scale_x_date(expand = c(0, 0)) +
    labs(x = "Recent 6 months", y = title)
}
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "South Korea/U.S. Foreign Exchange Rate"}
index_plot(Index, "USDKRW", "USD/KRW")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "KOSPI Index"}
index_plot(Index, "KOSPI", "KOSPI")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "KOSDAQ Index"}
index_plot(Index, "KOSDAQ", "KOSDAQ")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "S&P 500 Index"}
index_plot(Index, "S&P500", "S&P 500")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "NASDAQ Composite Index"}
index_plot(Index, "NASDAQ", "NASDAQ")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Wilshire US REIT Index"}
index_plot(Index, "REIT", "Wilshire REIT")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Gold Price"}
index_plot(Index, "Gold", "Gold")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Copper Price"}
index_plot(Index, "Copper", "Copper")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Crude Oil Price"}
index_plot(Index, "Oil", "Crude oil")
```

## Index trend (30 years)^[Data are from [Federal Reserve Bank of St. Louis](https://fred.stlouisfed.org/).]

```{r}
Shiller = read_html("https://www.multpl.com/shiller-pe/table/by-year", which = 1, header = T) %>% rename(Shiller = "\n\nValue\n\n\n\nValue\n")

Shiller$Date %<>% 
  str_match("([^ ,]+) ([^ ,]+), ([^ ,]+)") %>% 
  .[, -1] %>% 
  as_tibble %>% 
  setNames(c("m", "d", "y")) %>% 
  mutate(m = match(m, month.abb), date = str_c(y, m, d, sep = "-")) %>% 
  pull(date) %>% 
  as.Date

Shiller$Shiller %<>% as.numeric

Shiller %<>% rename(DATE = Date)

USGDP = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "GDP", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Quarterly&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

Wilshire5000 = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "WILL5000PRFC", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Daily&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

WilshireREIT = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "WILLREITIND", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Daily&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

Gold = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "GOLDAMGBD228NLBM", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Daily&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

Copper = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "PCOPPUSDM", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Monthly&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

WTI = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "DCOILWTICO", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Daily&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

USBond = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "IRLTLT01USM156N", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Monthly&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

AAA = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "DAAA", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Daily&fam=avg&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

USDKRW = read_csv(str_c("https://fred.stlouisfed.org/graph/fredgraph.csv?id=", "DEXKOUS", "&cosd=", thirtyyearsago, "&coed=", today,
                              "&fq=Daily&vintage_date=", today, "&revision_date=", today, "&nd=", thirtyyearsago), col_names = T)

USGDP %<>% mutate(GDP = as.numeric(GDP)) %>%
  mutate(year = format(DATE, "%Y"),
         month = format(DATE, "%m") %>% as.numeric)

Wilshire_monthly = Wilshire5000 %>% 
  mutate(WILL5000PRFC = as.numeric(WILL5000PRFC),
         year = format(DATE, "%Y"),
         month = format(DATE, "%m") %>% as.numeric,
         month = ((month - 1) %/% 3) * 3 + 1) %>%
  group_by(year, month) %>% summarise(WILL5000PRFC = mean(WILL5000PRFC, na.rm = T))

Buffett = full_join(USGDP, Wilshire_monthly) %>% mutate(Buffett = WILL5000PRFC/GDP)

US = list(Shiller, Wilshire5000, WilshireREIT, Gold, Copper, WTI, USBond, AAA, USDKRW) %>%
  reduce(full_join) %>%
  mutate(across(-DATE, as.numeric)) %>%
  filter(DATE >= thirtyyearsago) %>%
  arrange(DATE)

index_plot_fed = function(feddata, category, y) {
  category = enquo(category)
  feddata %>% 
    filter(!is.na(!!category)) %>%
    ggplot(mapping = aes(x = DATE, y = !!category)) +
    geom_line(color = "blue", size = 1) +
    scale_x_date(expand = c(0, 0)) +
    labs(x = "Recent 30 years", y = y)
}
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Wilshire 5000 Full Cap Price Index"}
index_plot_fed(US, WILL5000PRFC, "Wilshire 5000")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Wilshire US REIT Total Market Index"}
index_plot_fed(US, WILLREITIND, "Wilshire REIT")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Gold Fixing Price 10:30 A.M. (London time) in London Bullion Market, based in U.S. Dollars"}
index_plot_fed(US, GOLDAMGBD228NLBM, "Gold fixing price")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Global Price of Copper"}
index_plot_fed(US, PCOPPUSDM, "Copper price")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma"}
index_plot_fed(US, DCOILWTICO, "Crude oil price")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Long-Term Government Bond Yields: 10-year: Main (Including Benchmark) for the United States"}
index_plot_fed(US, IRLTLT01USM156N, "Government bond yield")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Moody's Seasoned AAA Corporate Bond Yield"}
index_plot_fed(US, DAAA, "AAA corporate bond yield")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Wilshire 5000 Full Cap Price Index/Gross Domestic Product"}
index_plot_fed(Buffett, Buffett, "Buffett indicator")
```

```{r, fig.width = 7, fig.height = 8/2.5, fig.cap = "Cyclically Adjusted P/E (CAPE) Ratio for S&P 500"}
index_plot_fed(US, Shiller, "Shiller P/E ratio")
```

## Asset correlation

```{r, fig.width = 7, fig.height = 5.5, fig.cap = "Pairwise correlation between stock matket index, bond yields, REIT index, gold price, oil price, and USD/KRW exchange rate over the last 30 years"}
USdaily = list(Wilshire5000, WilshireREIT, Gold, WTI, AAA, USDKRW) %>%
  reduce(full_join) %>%
  mutate(across(-DATE, as.numeric)) %>%
  arrange(DATE)

USmonthly = list(Copper, USBond) %>%
  reduce(full_join) %>%
  mutate(across(-DATE, as.numeric)) %>%
  arrange(DATE)

UScross = full_join(USdaily, USmonthly) %>% mutate(month = format(DATE, "%Y-%m")) %>% group_by(month) %>% summarise(across(-DATE, ~mean(., na.rm = T))) %>% arrange(month)

USdailycor = USdaily %>% 
  mutate(interval = cut(DATE, 6)) %>% 
  group_by(interval) %>% 
  group_map(~cor(select(., -DATE), use = "pairwise.complete.obs"))

USdailycor %<>% reduce(`+`) %>% divide_by(length(USdailycor))

USmonthlycor = USmonthly %>% 
  mutate(interval = cut(DATE, 6)) %>%
  group_by(interval) %>%
  group_map(~cor(select(., -DATE), use = "pairwise.complete.obs"))

USmonthlycor %<>% reduce(`+`) %>% divide_by(length(USmonthlycor))

UScrosscor = UScross %>% 
  mutate(interval = cut(row_number(), 6)) %>%
  group_by(interval) %>%
  group_map(~cor(.[names(select(USdaily, -DATE))], .[names(select(USmonthly, -DATE))], use = "pairwise.complete.obs"))

UScrosscor %<>% reduce(`+`) %>% divide_by(length(UScrosscor))

UScor = bind_rows(USdailycor %>% as_tibble(rownames = "var1") %>% pivot_longer(cols = -var1, names_to = "var2", values_to = "r"),
          USmonthlycor %>% as_tibble(rownames = "var1") %>% pivot_longer(cols = -var1, names_to = "var2", values_to = "r"),
          UScrosscor %>% as_tibble(rownames = "var1") %>% pivot_longer(cols = -var1, names_to = "var2", values_to = "r"),
          UScrosscor %>% t %>% as_tibble(rownames = "var1") %>% pivot_longer(cols = -var1, names_to = "var2", values_to = "r")) %>%
  pivot_wider(id_cols = var1, names_from = var2, values_from = r) %>%
  column_to_rownames("var1") %>% as.matrix

relabel = function(symbol) c(WILL5000PRFC = "Wilshire 5000", 
                             WILLREITIND = "Wilshire US REIT", 
                             GOLDAMGBD228NLBM = "Gold fixing price", 
                             PCOPPUSDM = "Copper price",
                             DCOILWTICO = "Crude oil price", 
                             IRLTLT01USM156N = "Government bond yield",
                             DAAA = "AAA corporate bond yield",
                             DEXKOUS = "USD/KRW exchange rate")[symbol]

colnames(UScor) %<>% relabel
rownames(UScor) %<>% relabel

Heatmap(UScor, 
        name = "Pearson's r", 
        width = unit(3, "inch"), height = unit(3, "inch"), 
        row_names_gp = gpar(fontsize = 10),
        column_names_gp = gpar(fontsize = 10),
        heatmap_legend_param = list(legend_height = unit(1.5, "inch")))
```