# About the author {#author .unnumbered}

Junghoon Shin is a Korean doctor, cancer scientist, and statistical programmer. He earned his MD and MSc from the [Seoul National University College of Medicine](https://medicine.snu.ac.kr/en) and PhD from the [Graduate School of Medical Science and Engineering](https://gsmse.kaist.ac.kr/e_main), [Korea Advanced Institute of Science and Technology](https://www.kaist.ac.kr/en/), where he conducted research primarily on the transcriptome dysregulation patterns observed in cancer cells which have a key role in the cancer development process. He completed his resident training at the Department of Internal Medicine, [Seoul National University Hospital](http://www.snuh.org/global/en/main.do) and earned his medical board certificate in 2018. He is currently working as a clinical fellow at the Division of Hematology and Medical Oncology, Department of Internal Medicine, [Seoul National University Hospital](http://www.snuh.org/global/en/main.do).

More recently, he has had a particular interest in artificial intelligence, business management, and obviously, investment. He started investing when he knew almost nothing about investing. Yet everything he invested in was soaring through the sky. He had no idea why his stocks shot up and it was a shame. It turned out that he had made his first-ever investment in the biggest bull market the world has seen over the last decade: recovery from the COVID-19 crash in 2020. He was very lucky that he made many poor investment decisions without paying the price as many others do. This free lesson was only made possible thanks to [Sehhoon Park](http://www.samsunghospital.com/home/reservation/common/doctorProfile.do?DR_NO=2548), who encouraged him to start investing, told him what to read and watch, and shared with him which companies seemed good to invest in and why. This project would not have been possible without Sehhoon's constant and genuine advice.

He still has a lot to learn about investment and wants to share what he learns with as many learners like him as possible (especially with his beloved family and friends who are still on the fence about investing their cold hard cash in ticker symbols on the screen). The stock market will continue to wobble with inevitable recessions and booms as it always has done. He aspires to develop an objective resource of information that can help all investors to discern signals from noise and make the right decision based on reasoning and not on feeling. He spends most of his out-of-work time designing his project while thinking, reading, and digging out early-stage companies that have a great mission, [moat](#moat), and fine management.\
\

**Contact the author**\
junghoonshin@kaist.ac.kr
