# (PART) Let's invest {-}

# My portfolio {#portfolio}

## Invested asset composition

```{r}
portfolio = drive_get("Investment/Investment") %>% read_sheet(sheet = "Portfolio")

allocation = drive_get("Investment/Investment") %>% read_sheet(sheet = "Asset allocation")

portfolio %<>%
  mutate(Class = factor(Class, levels = c("Stock", "REIT", "Bond", "Commodity", "Gold")),
         Region = factor(Region, levels = c("Korea", "USA", "Europe", "Emerging", "Global")))

allocation %<>%
  mutate(`Target proportion` = round(`Target proportion`, 3)) %>%
  filter(!(`Current proportion` == 0 & `Target proportion` == 0)) %>%
  mutate(Class = factor(Class, levels = c("Stock", "REIT", "Bond", "Commodity", "Gold")),
         Region = factor(Region, levels = c("Korea", "USA", "Europe", "Emerging", "Global")))
```

```{r, fig.height = 3.5, fig.cap = "Asset allocation"}
portfolio %>%
  ggplot(mapping = aes(x = 1, y = Weight)) +
  geom_bar(stat = "summary", fun = sum, position = "fill", mapping = aes(fill = Class), color = "black") +
  scale_y_continuous(breaks = pretty_breaks(), labels = function(x) {percent(rev(x))}) +
  scale_fill_manual(values = fill_color, drop = F, guide = guide_legend(title = NULL)) +
  coord_polar(theta = "y", direction = -1) +
  labs(x = NULL, y = NULL) +
  theme(panel.border = element_blank(), panel.grid = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank())
```

```{r, fig.height = 6.3, fig.cap = "Regional distribution of invested assets"}
portfolio %>%
  group_by(Class) %>%
  mutate(width = sqrt(sum(Weight))) %>%
  ungroup %>%
  ggplot(mapping = aes(x = 1 + width/2, y = Weight)) +
  geom_bar(stat = "summary", fun = sum, position = "fill", mapping = aes(fill = Region, width = width), color = "black") +
  scale_y_continuous(breaks = pretty_breaks(), labels = function(x) {percent(rev(x))}) +
  scale_fill_manual(values = fill_color, drop = F, guide = guide_legend(title = NULL)) +
  coord_polar(theta = "y", direction = -1) +
  facet_wrap(vars(Class), nrow = 2) +
  labs(x = NULL, y = NULL) +
  theme(panel.grid = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank())
```

```{r, fig.cap = "Sector distribution of stock investment"}
portfolio_stock = portfolio %>% 
  filter(Class == "Stock") %>%
  select(Name, Region, Weight) %>%
  mutate(Name = case_when(Name == "Hyundai Motor S2 Pref Shs" ~ "Hyundai Motor Co",
                          T ~ Name)) %>%
  left_join(company %>% select(Name, Industry)) %>% 
  mutate(Industry = case_when(is.na(Industry) ~ "Index Fund",
                              T ~ Industry) %>% factor %>% relevel("Index Fund"),
         Weight = Weight / sum(Weight))

portfolio_stock %>%
  ggplot(mapping = aes(x = Region, y = Weight)) +
  geom_bar(mapping = aes(fill = Industry), stat = "summary", fun = sum, color = "black", width = 0.7) +
  scale_y_continuous(expand = c(0, 0, 0.05, 0), labels = percent) +
  scale_fill_manual(values = fill_color, guide = guide_legend(title = "Sector")) +
  labs(x = "Market", y = "Proportion")
```

```{r, fig.height = 3.5, fig.cap = "Bond composition"}
portfolio_bond = portfolio %>% 
  filter(Class == "Bond") %>%
  select(Name, Region, Weight) %>%
  mutate(Sector = case_when(Region == "USA" & str_detect(Name, "T-NOTE") & str_detect(Name, "10") ~ "U.S. 10-year treasury note",
                            Name == "ARIRANG US Long-term Credit" ~ "U.S. long-term AAA-A corporate bond",
                            Region == "Korea" & str_detect(Name, "10") ~ "South Korea 10-year government bond",
                            T ~ "Others"),
         Weight = Weight / sum(Weight))

portfolio_bond %>%
  ggplot(mapping = aes(x = 1, y = Weight)) +
  geom_bar(mapping = aes(fill = Sector), stat = "summary", fun = sum, position = "fill", color = "black") +
  scale_y_continuous(breaks = pretty_breaks(), labels = function(x) {percent(rev(x))}) +
  scale_fill_manual(values = fill_color, guide = guide_legend(title = NULL)) +
  coord_polar(theta = "y", direction = -1) +
  labs(x = NULL, y = NULL) +
  theme(panel.border = element_blank(), panel.grid = element_blank(), axis.ticks.y = element_blank(), axis.text.y = element_blank())
```

## Current and target asset allocation

```{r}
allocation %<>%
  mutate(category = str_c(Class, Region, sep = " - ") %>% 
           replace(. == "Commodity - Global", "Commodity") %>%
           factor(levels = c(setdiff(levels(interaction(Class, Region, sep = " - ", lex.order = T)), "Commodity - Global"), "Commodity"))) %>%
  group_by(category) %>%
  summarise(across(c(`Current proportion`, `Target proportion`), sum)) %>%
  arrange(desc(category)) %>%
  mutate(current_y = cumsum(`Current proportion`) - `Current proportion`/2,
         target_y = cumsum(`Target proportion`) - `Target proportion`/2)
```

```{r}
f1 = allocation %>%
  ggplot(mapping = aes(x = 1, y = `Current proportion`)) +
  geom_col(mapping = aes(fill = category), position = "fill", color = "black") +
  geom_text(mapping = aes(x = 1.3, y = current_y, label = make_percent(`Current proportion`, 100)), hjust = 0.5, vjust = 0.5, size = 9 / .pt, family = "Lato") +
  scale_y_continuous(breaks = pretty_breaks(), labels = function(x) {percent(rev(x))}) +
  scale_fill_manual(values = fill_color, guide = guide_legend(title = NULL)) +
  coord_polar(theta = "y", direction = -1) +
  labs(title = "Current allocation", x = NULL, y = NULL) +
  theme(panel.border = element_blank(), panel.grid = element_blank(), axis.ticks.y = element_blank(), axis.text = element_blank())

f2 = allocation %>%
  ggplot(mapping = aes(x = 1, y = `Target proportion`)) +
  geom_col(mapping = aes(fill = category), position = "fill", color = "black") +
  geom_text(mapping = aes(x = 1.3, y = target_y, label = make_percent(`Target proportion`, 100)), hjust = 0.5, vjust = 0.5, size = 9 / .pt, family = "Lato") +
  scale_y_continuous(breaks = pretty_breaks(), labels = function(x) {percent(rev(x))}) +
  scale_fill_manual(values = fill_color, guide = guide_legend(title = NULL)) +
  coord_polar(theta = "y", direction = -1) +
  labs(title = "Target allocation", x = NULL, y = NULL) +
  theme(panel.border = element_blank(), panel.grid = element_blank(), axis.ticks.y = element_blank(), axis.text = element_blank())

ggarrange(f1, f2, common.legend = T, legend = "bottom")
```

