# Stock price trend {#price}

## Normalized stock price trend^[Only top 15 industry sectors are shown.]

```{r}
yahoo_to_name = function(Yahoo) company$Name[match(Yahoo, company$Yahoo)]

price_data = tq_get(company$Yahoo, get = "stock.prices", from = twoyearsago)

price_data %<>% 
  mutate(Name = yahoo_to_name(symbol)) %>% 
  left_join(company %>% select(Name, Industry))
```

```{r}
get_legend_nrow = function(close, industry) {
  max(round((close %>% filter(Industry == industry) %>% pull(Name) %>% unique %>% length)/3), 1)
}

get_legend_nrow = Vectorize(get_legend_nrow, "industry")

legend_key_size = theme_get()$legend.key.size %>% convertUnit("inch") %>% as.numeric

normalized_price_trend = function(price, industry) {
  price_subset = price %>% 
    filter(Industry == industry) %>%
    mutate(Name = clean_name(Name))
  
  base_date = price_subset %>% count(date) %>% arrange(desc(n), date) %>% slice(1) %>% pull(date)
  
  price_subset %<>% 
    group_by(Name) %>%
    mutate(normalized = adjusted/adjusted[date == base_date] * 100) %>%
    ungroup

  ncompany = length(unique(price_subset$Name))
  legend_nrow = max(round(ncompany/3), 1)
  
  g = price_subset %>%
    ggplot(mapping = aes(x = date, y = normalized)) +
    geom_line(mapping = aes(color = Name)) +
    scale_x_date(expand = c(0, 0)) +
    scale_color_manual(values = line_color[1:ncompany], 
                       guide = guide_legend(title = NULL, nrow = legend_nrow)) +
    labs(x = "Date", y = "Normalized closing price") +
    annotation_custom(segmentsGrob(x0 = unit(0.5, "npc"), 
                                   x1 = unit(0.5, "npc"), 
                                   y0 = unit(0, "npc"), 
                                   y1 = unit(1.1, "npc"),
                                   gp = gpar(lty = "dashed")),
                      xmin = base_date, xmax = base_date) +
    annotation_custom(textGrob(str_c("Normalized to 100 as of ", base_date), 
                               x = unit(0.5, "npc"),
                               y = unit(1.05, "npc"), 
                               hjust = ifelse(base_date < yearago, -0.03, 1.03), 
                               vjust = 0.5,
                               gp = gpar(fontfamily = "Lato", fontsize = 10)),
                      xmin = base_date, xmax = base_date) +
    theme(legend.position = "bottom", legend.key = element_rect(fill = "transparent"),
          plot.margin = unit(c(convertUnit(unit(0.35, "inch"), unitTo = "points") %>% as.numeric, 5.5, 5.5, 5.5), "points"))
  
  g_legend = get_legend(g)
  
  g = ggplot_gtable(ggplot_build(g + guides(color = F)))
  
  g$layout$clip[g$layout$name == "panel"] = "off"
  
  ggarrange(ggdraw(g), g_legend, nrow = 2, ncol = 1, heights = c(3.5, legend_nrow * legend_key_size + 0.1 * 2))
}

interesting_sectors = price_data %>% select(Name, Industry) %>% unique %>% count(Industry) %>% arrange(desc(n), Industry) %>% pull(Industry)

fig_height = 3.5 + get_legend_nrow(price_data, interesting_sectors) * legend_key_size + 0.1 * 2
```

```{r, fig.width = 7, fig.height = fig_height[1], fig.cap = interesting_sectors[1]}
normalized_price_trend(price_data, interesting_sectors[1])
```

```{r, fig.width = 7, fig.height = fig_height[2], fig.cap = interesting_sectors[2]}
normalized_price_trend(price_data, interesting_sectors[2])
```

```{r, fig.width = 7, fig.height = fig_height[3], fig.cap = interesting_sectors[3]}
normalized_price_trend(price_data, interesting_sectors[3])
```

```{r, fig.width = 7, fig.height = fig_height[4], fig.cap = interesting_sectors[4]}
normalized_price_trend(price_data, interesting_sectors[4])
```

```{r, fig.width = 7, fig.height = fig_height[5], fig.cap = interesting_sectors[5]}
normalized_price_trend(price_data, interesting_sectors[5])
```

```{r, fig.width = 7, fig.height = fig_height[6], fig.cap = interesting_sectors[6]}
normalized_price_trend(price_data, interesting_sectors[6])
```

```{r, fig.width = 7, fig.height = fig_height[7], fig.cap = interesting_sectors[7]}
normalized_price_trend(price_data, interesting_sectors[7])
```

```{r, fig.width = 7, fig.height = fig_height[8], fig.cap = interesting_sectors[8]}
normalized_price_trend(price_data, interesting_sectors[8])
```

```{r, fig.width = 7, fig.height = fig_height[9], fig.cap = interesting_sectors[9]}
normalized_price_trend(price_data, interesting_sectors[9])
```

```{r, fig.width = 7, fig.height = fig_height[10], fig.cap = interesting_sectors[10]}
normalized_price_trend(price_data, interesting_sectors[10])
```

```{r, fig.width = 7, fig.height = fig_height[11], fig.cap = interesting_sectors[11]}
normalized_price_trend(price_data, interesting_sectors[11])
```

```{r, fig.width = 7, fig.height = fig_height[12], fig.cap = interesting_sectors[12]}
normalized_price_trend(price_data, interesting_sectors[12])
```

```{r, fig.width = 7, fig.height = fig_height[13], fig.cap = interesting_sectors[13]}
normalized_price_trend(price_data, interesting_sectors[13])
```

```{r, fig.width = 7, fig.height = fig_height[14], fig.cap = interesting_sectors[14]}
normalized_price_trend(price_data, interesting_sectors[14])
```

```{r, fig.width = 7, fig.height = fig_height[15], fig.cap = interesting_sectors[15]}
normalized_price_trend(price_data, interesting_sectors[15])
```

## [Adjusted stock price trend](https://www.investopedia.com/terms/a/adjusted_closing_price.asp)

```{r, fig.width = 7, fig.height = 2.5 * length(unique(price_data$Name)), fig.cap = "Adjusted closing stock price over the last 2 years"}
price_data %>% 
  ggplot(mapping = aes(x = date, y = adjusted)) +
  geom_line(color = line_color[1]) +
  scale_x_date(expand = c(0, 0)) +
  labs(x = "Date", y = "Adjusted closing price") +
  facet_grid(rows = vars(Name), scales = "free_y")
```

## Stock price correlation^[Industry sector classification is based on data from [here](http://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/pedata.html).]

```{r, include = F}
price_cor = price_data %>% 
  mutate(Name = clean_name(Name)) %>%
  select(Name, date, adjusted) %>%
  pivot_wider(id_cols = date, names_from = Name, values_from = adjusted) %>%
  column_to_rownames("date") %>%
  cor(use = "pairwise.complete.obs")

company_annotation = company %>% 
  select(Name, `Broad group`, Country, Industry) %>% 
  mutate(Name = clean_name(Name)) %>%
  column_to_rownames("Name") %>% 
  .[rownames(price_cor), ]

n_industry = company_annotation$Industry %>% unique %>% length

broad_group_color = fill_color[1:length(unique(company_annotation$`Broad group`))] %>% setNames(sort(unique(company_annotation$`Broad group`)))
country_color = fill_color[1:length(unique(company_annotation$Country))] %>% setNames(sort(unique(company_annotation$Country)))
industry_color = fill_color[1:length(unique(company_annotation$Industry))] %>% setNames(sort(unique(company_annotation$Industry)))

column_annotation = HeatmapAnnotation(df = company_annotation,
                                      col = list(Industry = industry_color,
                                                 Country = country_color,
                                                 `Broad group` = broad_group_color),
                                      annotation_name_gp = gpar(fontsize = 8),
                                      annotation_legend_param = list(`Broad group` = list(grid_width = unit(4, "mm"),
                                                                                          grid_height = unit(4, "mm"),
                                                                                          title_gp = gpar(fontsize = 8, fontface = "bold"),
                                                                                          labels_gp = gpar(fontsize = 7)),
                                                                     Country = list(grid_width = unit(4, "mm"),
                                                                                    grid_height = unit(4, "mm"),
                                                                                    title_gp = gpar(fontsize = 8, fontface = "bold"),
                                                                                    labels_gp = gpar(fontsize = 7)),
                                                                     Industry = list(ncol = 2, 
                                                                                     grid_width = unit(4, "mm"),
                                                                                     grid_height = unit(4, "mm"),
                                                                                     title_gp = gpar(fontsize = 8, fontface = "bold"),
                                                                                     labels_gp = gpar(fontsize = 7))))

h = price_cor %>% Heatmap(name = "Pearson's r",
                        width = unit(5.25, "inch"), height = unit(5.25, "inch"),
                        show_column_names = F, show_column_dend = T,
                        show_row_names = T, show_row_dend = F,
                        row_names_gp = gpar(fontsize = 6),
                        heatmap_legend_param = list(legend_height = unit(ceiling(n_industry/2) * 4, "mm"),
                                                    grid_width = unit(4, "mm"),
                                                    title_gp = gpar(fontsize = 8, fontface = "bold"),
                                                    labels_gp = gpar(fontsize = 7)),
                        top_annotation = column_annotation) %>% 
  draw(merge_legend = T, heatmap_legend_side = "bottom")

h_height = h@ht_list_param$height %>% as.numeric %>% conv_unit("mm", "inch")
```

```{r, fig.width = 7, fig.height = h_height + 0.2, fig.cap = "Pairwise correlation between closing prices of my watchlist over the last 2 years"}
h
```